# 1. Numpy

In [1]:
import numpy as np

In [2]:
a= [[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
a

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [3]:
b = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [4]:
print(a.shape)

AttributeError: 'list' object has no attribute 'shape'

In [5]:
print (b.shape)

(4, 3)


# 2. Accessing individual elements of array

type 1

In [6]:
print (b)
b[0,0],b[3,2],b[1,1]

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


(1, 12, 5)

type 2 

b[[0,3,1],[0,2,1]]

type 3 

In [7]:
x = np.arange(4)
x

array([0, 1, 2, 3])

In [8]:
y = np.array([0,2,0,1])
y

array([0, 2, 0, 1])

In [9]:
b[x,y]

array([ 1,  6,  7, 11])

# 3.Conditional Access of Arrays 

In [10]:
b>5

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [11]:
c= b[b>5]
c

array([ 6,  7,  8,  9, 10, 11, 12])

In [12]:
c.shape

(7,)

In [13]:
b[(b>5)|(b<=10)] , b[(b>5)&(b<=10)]

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]),
 array([ 6,  7,  8,  9, 10]))

# 4.Array Operation

In [14]:
x = np.array([[10,20],[30,40]])
y = np.array([[5,6],[7,8]])
print("x>\n",x)
print("y>\n",y)


x>
 [[10 20]
 [30 40]]
y>
 [[5 6]
 [7 8]]


In [15]:
print("x+y>\n",x+y)
print("\nx-y >\n",x-y)
print("\nx*y >\n",x*y)
print("\nx/y >\n",x/y)
print("\nx%y >\n",x%y)
print("\nx//y >\n",x//y)


x+y>
 [[15 26]
 [37 48]]

x-y >
 [[ 5 14]
 [23 32]]

x*y >
 [[ 50 120]
 [210 320]]

x/y >
 [[2.         3.33333333]
 [4.28571429 5.        ]]

x%y >
 [[0 2]
 [2 0]]

x//y >
 [[2 3]
 [4 5]]


In [16]:
print("x+y>\n",np.add(x,y))
print("x-y>\n",np.subtract(x,y))
print("x*y>\n",np.multiply(x,y))
print("x/y>\n",np.divide(x,y))

x+y>
 [[15 26]
 [37 48]]
x-y>
 [[ 5 14]
 [23 32]]
x*y>
 [[ 50 120]
 [210 320]]
x/y>
 [[2.         3.33333333]
 [4.28571429 5.        ]]


In [17]:
#Matrix Multiplication

In [18]:
x.dot(y)

array([[190, 220],
       [430, 500]])

In [19]:
# transpose of a matrix
print("x >\n",x)
print("x >\n",x.T)

x >
 [[10 20]
 [30 40]]
x >
 [[10 30]
 [20 40]]


In [20]:
# if order of matrix doesn't match for a matrix multipilcation

In [21]:
x = np.array([[2,5,6],[7,2,6]])
print("x >\n",x)
y = np.array([[1,2,9],[7,5,4]])
print("\n y>\n",y)

x >
 [[2 5 6]
 [7 2 6]]

 y>
 [[1 2 9]
 [7 5 4]]


In [22]:
x.shape


(2, 3)

In [23]:
y.shape

(2, 3)

In [24]:
x.dot(y)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [25]:
x.dot(y.T)

array([[66, 63],
       [65, 83]])

In [26]:
# or

In [27]:
y = y.reshape(3,2)
y

array([[1, 2],
       [9, 7],
       [5, 4]])

In [28]:
x.dot(y)

array([[77, 63],
       [55, 52]])

In [29]:
import math as m

In [30]:
m.sqrt(36)

6.0

In [31]:
a=[256,625,225,169]
m.sqrt(a)

TypeError: must be real number, not list

In [32]:
np.sqrt(a)

array([16., 25., 15., 13.])

# 5.Subsetting an array

In [33]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [34]:
b = a[:2,1:3]
b

array([[2, 3],
       [5, 6]])

In [35]:
c = a[:2,1:3].copy()
c

array([[2, 3],
       [5, 6]])

In [36]:
c[0,0] = 77
print(c)
print(a)

[[77  3]
 [ 5  6]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [37]:
# now try to change in matrix b

In [38]:
b[0,0]=66
print(b)
print(a)

[[66  3]
 [ 5  6]]
[[ 1 66  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# 6.Numpy Functions

In [39]:
#Quick ways of creating some aarays with default value

In [40]:
#All zeros

In [41]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
#All ones 

In [43]:
np.ones((3,2),dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [44]:
#All constants

In [45]:
np.full((2,2),m.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

In [46]:
#Identify matrix

In [47]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [48]:
np.random.random()

0.31790389616130776

In [49]:
np.random.random((3,2))

array([[0.78548255, 0.51983787],
       [0.38297043, 0.11739105],
       [0.85842853, 0.21284483]])

In [50]:
## * (b-a)*np.random.random()+a

In [51]:
(90-25)*np.random.random((4,3))+25

array([[64.22453209, 68.89909447, 76.15656895],
       [76.2629472 , 74.96778558, 42.91337864],
       [55.9947944 , 88.88097219, 49.4732337 ],
       [46.54649992, 37.14280496, 26.74723147]])

In [52]:
a

array([[ 1, 66,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [53]:
np.sum(a, axis=1)

array([70, 15, 24, 33])

In [54]:
h=np.sum(a, axis=1)

In [55]:
np.tile(h,4)

array([70, 15, 24, 33, 70, 15, 24, 33, 70, 15, 24, 33, 70, 15, 24, 33])

In [56]:
np.tile(h, (4,1))

array([[70, 15, 24, 33],
       [70, 15, 24, 33],
       [70, 15, 24, 33],
       [70, 15, 24, 33]])

In [57]:
a

array([[ 1, 66,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [58]:
a.all() # if all elements are non zeros

True

In [59]:
a.any() # return true if any value is nonzero  and false if

True

In [60]:
x

array([[2, 5, 6],
       [7, 2, 6]])

In [61]:
x.argmax()

3